import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="Navbar">
          {""}

          <button className="Navbar-button">
            <Link href={"/"}> home</Link>
          </button>

          <button className="Navbar-button">
            <Link href={"/about"}> about</Link>
          </button>

          <button className="Navbar-button">
            <Link href={"/contact"}> contact</Link>  
          </button>

          <button className="Navbar-button">
            <Link href={"/users"}> users</Link>
          </button>
          
        </div>

        {children}
      </body>
    </html>
  );
}
